"""time stamp added

Revision ID: 6406566b7bfa
Revises: d7bfe25e8964
Create Date: 2022-04-24 13:56:52.043049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6406566b7bfa'
down_revision = 'd7bfe25e8964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaderboard', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leaderboard', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leaderboard', type_='foreignkey')
    op.drop_column('leaderboard', 'user_id')
    # ### end Alembic commands ###
