"""inital commit

Revision ID: 883f48deb34e
Revises: 
Create Date: 2022-04-24 12:35:36.269595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '883f48deb34e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('played', sa.Integer(), nullable=True),
    sa.Column('won', sa.Integer(), nullable=True),
    sa.Column('draw', sa.Integer(), nullable=True),
    sa.Column('lose', sa.Integer(), nullable=True),
    sa.Column('goals_for', sa.Integer(), nullable=True),
    sa.Column('goals_against', sa.Integer(), nullable=True),
    sa.Column('goals_difference', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_id'), 'leaderboard', ['id'], unique=False)
    op.create_table('stats_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=True),
    sa.Column('away_team', sa.String(), nullable=True),
    sa.Column('home_team_goals', sa.Integer(), nullable=True),
    sa.Column('away_team_goals', sa.Integer(), nullable=True),
    sa.Column('home_team_possession', sa.Integer(), nullable=True),
    sa.Column('away_team_possession', sa.Integer(), nullable=True),
    sa.Column('home_team_fouls', sa.Integer(), nullable=True),
    sa.Column('away_team_fouls', sa.Integer(), nullable=True),
    sa.Column('home_team_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('away_team_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('home_team_red_cards', sa.Integer(), nullable=True),
    sa.Column('away_team_red_cards', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stats_sheet_id'), 'stats_sheet', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_stats_sheet_id'), table_name='stats_sheet')
    op.drop_table('stats_sheet')
    op.drop_index(op.f('ix_leaderboard_id'), table_name='leaderboard')
    op.drop_table('leaderboard')
    # ### end Alembic commands ###
