"""time stamp added

Revision ID: d7bfe25e8964
Revises: 883f48deb34e
Create Date: 2022-04-24 13:30:20.357519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7bfe25e8964'
down_revision = '883f48deb34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats_sheet', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('stats_sheet', sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats_sheet', 'time_updated')
    op.drop_column('stats_sheet', 'time_created')
    # ### end Alembic commands ###
