"""test database creation

Revision ID: e4c54aa91988
Revises: 6406566b7bfa
Create Date: 2022-04-25 17:08:01.928236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c54aa91988'
down_revision = '6406566b7bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
